apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-17R5U6LZ5PQ8L
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::<ACCOUNT_ID>:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-07T18:33:19Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2293"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 9264e992-8f0d-42bb-94ef-e30b424bc7ef
